
name: "Deployment pipeline"

on:
  workflow_dispatch:
    inputs:
      use_purge:
        type: boolean
        description: Purge the cdn content.
        default: false
      tier:
        type: choice
        description: "Tier"
        required: true
        options:
          - uat
          - dev
          - prod
      customer:
        type: choice
        description: "The customer tenant to deploy"
        required: true
        options:
          - vvv
          - ppp

# We choose the runner-tags based on the customer
jobs:

  # get-resource-group:
  #   runs-on: ['ubuntu-20.04']
  #   outputs:
  #     resource_group_name: ${{ steps.get_resource_group.outputs.resource_group_name }}
  #   steps:
  #     - id: get_resource_group
  #       run: |
  #         if [ '${{ inputs.tier }}' == 'dev' ]
  #         then
  #           echo "::set-output name=resource_group_name::test"
  #         elif [ '${{ inputs.tier }}' == 'uat' ]
  #         then
  #           echo "::set-output name=resource_group_name::qa"
  #         elif [ '${{ inputs.tier }}' == 'prod' ]
  #         then
  #           echo "::set-output name=resource_group_name::production"
  #         fi
  main:
    # needs: [ get-resource-group ]
    environment: ${{inputs.customer}}-${{ inputs.tier }}
    runs-on: ['ubuntu-20.04']
    steps:
      - run: echo "Starting..."
      - uses: actions/checkout@v3
      - id: get-resource-group-name
        name: Get Resource Group
        if: ${{ inputs.use_purge }}
        run: |
          echo "${{ vars.ENVIRONMENT_STAGE }}"
          echo ${{ vars.ENV_CONTEXT_VAR }}
          if [ '${{ inputs.tier }}' == 'dev' ]
          then
            echo "::set-output name=resource_group::sps-dev"
            echo "::set-output name=subscription_id::${{vars.RESOURCE_GROUP}}"
            
          elif [ '${{ inputs.tier }}' == 'uat' ]
          then
            echo "::set-output name=resource_group::ssp-uat"
            echo "::set-output name=subscription_id::${{vars.RESOURCE_GROUP}}"

          elif [ '${{ inputs.tier }}' == 'prod' ]
          then
            echo "set the output"
            echo "::set-output name=resource_group::abc-production"
            echo "::set-output name=subscription_id::${{vars.RESOURCE_GROUP}}"
          fi
      - name: Purge CDN Endpoints
        if: ${{ inputs.use_purge }}
        uses: ./.github/workflows/actions/purge-cdn-endpoints
        with:
          tier: "${{inputs.tier}}"
          resource_group: ${{steps.get-resource-group-name.outputs.resource_group}}
          subscription_id: ${{steps.get-resource-group-name.outputs.subscription_id}}
