name: "MAIN"
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/workflows/actions/hello-world
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - id: get-resource-group
        name: Get Resource Group
        run: |
          if [ 'dev' == 'dev' ]
          then
            echo "::set-output name=resource_group::dd-rg"
          elif [ '${{ inputs.tier }}' == 'uat' ]
          then
            echo "::set-output name=resource_group::sdsd-rg"
          elif [ '${{ inputs.tier }}' == 'prod' ]
          then
            echo "::set-output name=resource_group::sdsdewc"
          fi
      - name: Purge CDN Endpoints
        uses: ./.github/workflows/actions/purge-cdn-endpoints
        with:
          tier: "dev"
          resource_group: ${{steps.get-resource-group.outputs.resource_group}}
      - name: test1 new Workflow
        run: | 
          echo "New Workflow test1 started"
          echo "added new step in test1 branch"