on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/workflows/actions/hello-world
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - name: Purge CDN Endpoints
        uses: ./.github/workflows/actions/purge-cdn-endpoints
        with:
          tier: "dev"
          resource_group: "rg_yuy"