name: Matrix Test
on: 
    workflow_dispatch
jobs:
  setupMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        nodes=("node1" "node2" "node3")
        echo "::set-output name=matrix::${nodes[@]}"
  runAgainstMatrix:
    needs: setupMatrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setupMatrix.outputs.matrix) }}
    steps:
    - run: echo ${matrix[2]}
