name: Matrix Test
on: 
    workflow_dispatch
jobs:
  setupMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::node1,node2,node3"
  runAgainstMatrix:
    needs: setupMatrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setupMatrix.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.node }}
