name: Matrix Test
on: 
  workflow_dispatch:
    inputs:
      restart_tcpdump:
        description: 'Restart tcpdump command'
        default: true
jobs:
  setupMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        nodes=(node1 node2 node3)
        # Create a JSON array from the node names
        json_array="["
        for node in "${nodes[@]}"; do
          json_array+="\"$node\","
        done
        json_array="${json_array%,}" # Remove the trailing comma
        json_array+="]"
        echo "::set-output name=matrix::{\"node\":$json_array}"
  runAgainstMatrix:
    needs: setupMatrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setupMatrix.outputs.matrix) }}
    
    steps:
        - name: Enter into the shell
          run: echo into the shell ${{matrix.node}}
          
          shell: bash
          
        - name: Run the TCP command
          run: |
            echo run the tcp command ${{matrix.node}}
            node=${{ matrix.node }}
            current_time=$(date "+%Y-%m-%d-%H-%M-%S")
            blob_folder_name="$node"_"$current_time"
            echo folder name is : $blob_folder_name
          shell: bash
          
        - name: clean up the TCP logs
          run: echo clear the tcp logs ${{matrix.node}}
          shell: bash
        - name: Restart tcpdump
          if: ${{ inputs.restart_tcpdump == 'true' }}
          run: |
            echo "Starting new process..."
          shell: bash
