name: Matrix Test
on: 
    workflow_dispatch
jobs:
  setupMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        nodes=(node1 node2 node3)
        # Create a JSON array from the node names
        json_array="["
        for node in "${nodes[@]}"; do
          json_array+="\"$node\","
        done
        json_array="${json_array%,}" # Remove the trailing comma
        json_array+="]"
        echo "$json_array" > nodes.json
        echo "::set-output name=matrix::{\"node\":$json_array}"
  runAgainstMatrix:
    needs: setupMatrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setupMatrix.outputs.matrix) }}
    steps:
    - run: echo ${matrix.node}
