name: Print some text every 3rd minute
on:
  schedule:
    - cron: '1/3 * * * *'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      text_to_print:
        description: 'What text do you want to print?'
        required: true
        type: choice
        options:
          - dev
          - int
          - uat
        default: 'dev'
      color:
        description: 'Select the cluster color.'
        required: true
        type: choice
        options:
          - blue
          - green
        default: 'blue'
env:
  TIER: Monday

jobs:
  print_text:
    runs-on: ['ubuntu-20.04']
    steps:
      - name: Set the variables
        env:
          DEFAULT_MESSAGE: 'prod' # here is the default message
          DEFAULT_COLOR: 'blue'
        run: |
          MESSAGE=${{ github.event.inputs.text_to_print || github.env.DEFAULT_MESSAGE }} >> $GITHUB_ENV
          #echo "MESSAGE=${{ github.event.inputs.text_to_print || github.env.DEFAULT_MESSAGE }}" >> $GITHUB_ENV
          echo MESSAGE112=${{ toJSON(vars.COLOR_TO_RESTART) }}
          
          IFS="," read -a myarray <<< ${{ vars.COLOR_TO_RESTART }}
          for i in "${myarray[@]}"; do
            echo "Value: ${i}"
            echo "Value: ${i%.*}"
          done
          echo COLOR=${{ github.event.inputs.color || github.env.DEFAULT_COLOR }} >> $GITHUB_ENV
          echo tier ${MESSAGE}  ${TIER} and message 
          echo "Step 1 Kolkata red error -n kolkata consistent --hyd abc-$MESSAGE-$COLOR-xyz"
          echo "default  --hyd abc-$DEFAULT_MESSAGE-$DEFAULT_COLOR-xyz"
          
      - name: Print some text step 2 
        run: |
          echo step 2 Kolkata red error -n kolkata consistent --hyd abc-$MESSAGE-$COLOR-xyz-  "${{ github.env.DEFAULT_MESSAGE }}"
        
#   print_text1:
#     runs-on: ['ubuntu-20.04']
#     steps:
#       - name: Set the variables2
#         env:
#           DEFAULT_MESSAGE: 'prod2' # here is the default message
#           DEFAULT_COLOR: 'blue'
#         shell: bash
#         run: |
#           echo "MESSAGE=${{ github.event.inputs.text_to_print || env.DEFAULT_MESSAGE }}"  >> $GITHUB_ENV
#           echo "COLOR=${{ github.event.inputs.color || env.DEFAULT_COLOR }}"  >> $GITHUB_ENV
#           echo step 2-  $TIER
#       - name: Print some text
#         run: |
#           echo "Kolkata red error -n kolkata consistent --hyd abc-$MESSAGE-$COLOR-xyz"
#           echo "default in step 2 Kolkata red error -n kolkata consistent --hyd abc-$DEFAULT_MESSAGE-$DEFAULT_COLOR-xyz"
        
